- name: Create a volume
  shell: |
    VOLUME_NAME='{{ virtual_machine_names[item.hostname] }}'
    virsh \
      --connect '{{ libvirt.libvirt_connection_uri }}' \
      vol-info \
      --pool '{{ libvirt.pool_name }}' \
      "$VOLUME_NAME"
    if [ $? -ne 0 ]; then
      virsh \
        --connect  '{{ libvirt.libvirt_connection_uri }}' \
        vol-create-as \
        --pool '{{ libvirt.pool_name }}' \
        --name "$VOLUME_NAME" \
        --capacity {{ item.disk_gb }}G \
        --format qcow2 \
        --allocation 0 || exit 1
      echo CHANGED
    fi
  register: libvirt_volume
  changed_when: libvirt_volume is failed or libvirt_volume.stdout | regex_search('CHANGED')
  become: True

- name: Create a virtual machine {{ virtual_machine_names[item.hostname] }}
  virt:
    uri: '{{ libvirt.libvirt_connection_uri }}'
    command: define
    xml: '{{ lookup("template", libvirt.domain_template) }}'
  become: True

- name: Power on virtual machine {{ virtual_machine_names[item.hostname] }}
  virt:
    uri: '{{ libvirt.libvirt_connection_uri }}'
    name: '{{ item.hostname }}.{{ openshift_install_config.cluster_domain }}'
    state: running
  become: True
