- name: Generate an ISO image
  import_role:
    name: openshift_common
    tasks_from: create_boot_iso.yml

- name: Upload ISO image {{ boot_iso_filename }} to vSphere
  vsphere_copy:
    hostname: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username }}'
    password: '{{ vsphere.vcenter_password }}'
    datacenter: '{{ vsphere.datacenter_name }}'
    datastore: '{{ vsphere.datastore_name }}'
    src: '{{ boot_iso_filename }}'
    path: '{{ boot_iso_filename | basename }}'
    timeout: 300
    validate_certs: '{{ vsphere.validate_certs }}'

- name: Attach CD-ROM with the boot ISO inserted
  vmware_guest:
    hostname: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username }}'
    password: '{{ vsphere.vcenter_password }}'
    name: '{{ virtual_machine_names[item.hostname] }}'
    cdrom:
      - type: iso
        iso_path: '[{{ vsphere.datastore_name }}] {{ boot_iso_filename | basename }}'
        # Ansible <= 2.9.7 supports ide controller only. Switch to sata controller
        # when available as that one will allow for device hot-remove
        controller_type: ide
        controller_number: 0
        unit_number: 0
    validate_certs: '{{ vsphere.validate_certs }}'

- name: Set virtual machine {{ item.hostname }} to boot from the ISO
  vmware_guest_boot_manager:
    hostname: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username }}'
    password: '{{ vsphere.vcenter_password }}'
    name: '{{ virtual_machine_names[item.hostname] }}'
    boot_order:
      - cdrom
    boot_delay: 0
    validate_certs: '{{ vsphere.validate_certs }}'
