- name: Check that ignition data is a valid JSON
  set_fact:
    dummy: '{{ lookup("template", "files/vsphere/append.ign", convert_data=False) | from_json }}'
  with_items: '{{ openshift_cluster_hosts }}'
