- name: Give VM enough time to boot from CD-ROM before detaching it
  pause:
    seconds: 15

- name: Go back to booting from the first hard disk
  vmware_guest_boot_manager:
    hostname: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username }}'
    password: '{{ vsphere.vcenter_password }}'
    name: '{{ virtual_machine_names[item.hostname] }}'
    boot_order:
      - disk
    validate_certs: '{{ vsphere.validate_certs }}'

- name: Eject CD-ROM
  vmware_guest:
    hostname: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username }}'
    password: '{{ vsphere.vcenter_password }}'
    name: '{{ virtual_machine_names[item.hostname] }}'
    cdrom:
      - type: none
        controller_number: 0
        unit_number: 0
    validate_certs: '{{ vsphere.validate_certs }}'
