- name: Compute virtual machine names
  import_role:
    name: openshift_common
    tasks_from: compute_vm_names.yml

- name: Retrieve all machines in the folder {{ vsphere.target_folder }}
  vmware_vm_info:
    hostname: "{{ vsphere.vcenter_hostname }}"
    username: "{{ vsphere.vcenter_username }}"
    password: "{{ vsphere.vcenter_password }}"
    folder: "/{{ vsphere.datacenter_name }}/vm/{{ vsphere.target_folder }}"
    vm_type: vm
    validate_certs: "{{ vsphere.validate_certs }}"
  register: vsphere_vms

- name: Define existing virtual machines
  set_fact:
    vsphere_existing_vms: '{{ vsphere_vms.virtual_machines | json_query("[*].guest_name") }}'
