- name: Install prerequisites
  import_tasks: prereqs.yml

- name: Configure the installer
  import_tasks: config.yml

- name: Run some checks before the installation
  import_tasks: check.yml

- name: Run the installation
  import_tasks: run.yml

- name: Wait for the bootstrap to complete
  import_role:
    name: openshift_generic
    tasks_from: wait.yml
