- name: Install vSphere Python SDK used by Ansible to talk to vSphere
  yum:
    name: '{{ rpm_name["python-pyvmomi"] }}'
    state: present
  become: True

- name: Check that ignition data is a valid JSON
  set_fact:
    dummy: '{{ lookup("template", "files/vsphere/append.ign", convert_data=False) | from_json }}'
  with_items: '{{ openshift_cluster_hosts }}'

- name: Ensure required directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ helper.vsphere_dir }}'

- name: Download Red Hat CoreOS OVA template {{ coreos.vmware_ova_url }}
  get_url:
    url: '{{ coreos.vmware_ova_url }}'
    dest: '{{ helper.vsphere_dir }}/{{ coreos.vmware_ova_url | basename }}'
    checksum: 'sha256:{{ coreos.sha256sum_url }}'