- name: Create cluster folder
  vcenter_folder:
    hostname: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username }}'
    password: '{{ vsphere.vcenter_password }}'
    datacenter: '{{ vsphere.datacenter_name }}'
    folder_name: '{{ vsphere.cluster_name }}'
    folder_type: vm
    validate_certs: no
    state: present

- name: Upload Red Hat CoreOS OVA template
  vmware_deploy_ovf:
    hostname: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username }}'
    password: '{{ vsphere.vcenter_password }}'
    datacenter: '{{ vsphere.datacenter_name }}'
    cluster: '{{ vsphere.cluster_name }}'
    datastore: '{{ vsphere.datastore_name }}'
    folder: '/{{ vsphere.datacenter_name }}/vm/{{ vsphere.cluster_name }}'
    name: '{{ vsphere.template_name }}'
    allow_duplicates: no
    disk_provisioning: thin
    networks: '{}'
    ova: '{{ helper.vsphere_dir }}/{{ coreos.vmware_ova_url | basename }}'
    power_on: no
    validate_certs: no

- name: Create a virtual machine from a template
  vmware_guest:
    hostname: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username }}'
    password: '{{ vsphere.vcenter_password }}'
    datacenter: '{{ vsphere.datacenter_name }}'
    cluster: '{{ vsphere.cluster_name }}'
    folder: '{{ vsphere.target_folder }}'
    name: '{{ item.hostname }}.{{ openshift_install_config.cluster_domain }}'
    template: '{{ vsphere.template_name }}'
    customvalues:
      - key: guestinfo.ignition.config.data.encoding
        value: base64
      - key: guestinfo.ignition.config.data
        value: '{{ lookup("template", "files/vsphere/append.ign", convert_data=False) | b64encode }}'
      - key: disk.EnableUUID
        value: 'TRUE'
    disk:
      - size_gb: '{{ item.disk_gb }}'
        type: thin
        datastore: '{{ vsphere.datastore_name }}'
    hardware:
      memory_mb: '{{ item.memory_gb * 1024 }}'
      num_cpus: '{{ item.num_cpus }}'
      scsi: paravirtual
      hotadd_cpu: False
      hotremove_cpu: False
      hotadd_memory: False
    networks:
      - name: '{{ vsphere.network_name }}'
        mac: '{{ item.macaddr }}'
    wait_for_ip_address: no
    validate_certs: no
    state: present
  with_items: '{{ openshift_cluster_hosts }}'

- name: Power on virtual machine
  vmware_guest:
    hostname: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username }}'
    password: '{{ vsphere.vcenter_password }}'
    name: '{{ item.hostname }}.{{ openshift_install_config.cluster_domain }}'
    validate_certs: no
    state: poweredon
  with_items: '{{ openshift_cluster_hosts }}'
