- name: Power on virtual machine
  vmware_guest:
    hostname: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username }}'
    password: '{{ vsphere.vcenter_password }}'
    name: '{{ virtual_machine_names[item.hostname] }}'
    validate_certs: False
    state: poweredon
  with_items: '{{ openshift_cluster_hosts }}'