- name: Define pull secret host port
  set_fact:
    pull_secret_host_port: '{{ mirror_registry.connect_host }}:{{ mirror_registry.connect_port }}'

- name: Define pull secret credentials
  set_fact:
    pull_secret_credentials: '{{ [ mirror_registry.credentials.username, mirror_registry.credentials.password ] | join(":") | b64encode }}'

- name: Compile pull secret json
  set_fact:
    pull_secret_json: >
      {{ (mirror_registry.pull_secret | from_json) | combine({ 'auths': { pull_secret_host_port: { 'auth': pull_secret_credentials, 'email': 'user@example.com' }}}, recursive=True) }}

- name: Save the pull secret to {{ helper.mirror_registry_dir }}/pull-secret.json
  copy:
    dest: '{{ helper.mirror_registry_dir }}/pull-secret.json'
    content: '{{ pull_secret_json }}'
