- name: Define mirror registry host port
  set_fact:
    add_registry_host_port: '{{ mirror_registry.connect_host }}:{{ mirror_registry.connect_port }}'

- name: Define mirror registry credentials
  set_fact:
    add_registry_credentials: '{{ [ mirror_registry.credentials.username, mirror_registry.credentials.password ] | join(":") | b64encode }}'

- name: Create a combined pull secret
  set_fact:
    pull_secret_json: >
      {{ (mirror_registry.pull_secret | from_json) | combine({ 'auths': { add_registry_host_port: { 'auth': add_registry_credentials, 'email': 'user@example.com' }}}, recursive=True) }}

- name: Save the combined pull secret to {{ helper.mirror_registry_dir }}/pull-secret.json
  copy:
    dest: '{{ helper.mirror_registry_dir }}/pull-secret.json'
    content: '{{ pull_secret_json }}'
