- name: Create openshift-install client that downloads container images from the mirror
  command: |
    oc adm release extract \
      --registry-config pull-secret.json \
      --command openshift-install \
      {{ mirror_registry.mirror_to }}:{{ mirror_registry.mirror_to_release }}
  args:
    chdir: '{{ helper.mirror_registry_dir }}'
    creates: '{{ helper.mirror_registry_dir }}/openshift-install'

- name: Get installer's content location
  command: |
    {{ helper.mirror_registry_dir }}/openshift-install version
  register: installer_version

- name: Show installer's content location
  debug:
    var: installer_version.stdout_lines
