- name: Remove an existing mirror-registry container
  command: podman rm --force mirror-registry
  ignore_errors: True
  become: True

- name: Create a mirror-registry container
  command: '{{ helper.mirror_registry_dir }}/mirror_create.sh'
  become: True

- name: Generate container-mirror-registry systemd script
  command: podman generate systemd mirror-registry
  changed_when: False
  register: container_systemd
  become: True

- name: Install container-mirror-registry systemd script
  copy:
    dest: /etc/systemd/system/container-mirror-registry.service
    content: '{{ container_systemd.stdout }}'
  notify: Restart container-mirror-registry
  become: True

- name: Reload systemd unit configuration
  command: systemctl --system daemon-reload
  become: yes
