- name: Copy the mirror sync script
  template:
    src: mirror_sync.sh
    dest: '{{ helper.mirror_registry_dir }}'
    mode: '0755'

- name: Waiting since {{ lookup("pipe", "date +%r") }} for the mirror sync to complete
  command: '{{ helper.mirror_registry_dir }}/mirror_sync.sh'
  register: mirror_command

- debug:
    var: mirror_command.stderr_lines

- debug:
    var: mirror_command.stdout_lines

- name: Save standard error to file {{ helper.mirror_registry_dir }}/mirror_sync.stderr.txt
  copy:
    dest: '{{ helper.mirror_registry_dir }}/mirror_sync.stderr.txt'
    content: '{{ mirror_command.stderr }}'

- name: Save standard output to file {{ helper.mirror_registry_dir }}/mirror_sync.stdout.txt
  copy:
    dest: '{{ helper.mirror_registry_dir }}/mirror_sync.stdout.txt'
    content: '{{ mirror_command.stdout }}'
    backup: True

- name: Disconnected installation instructions
  set_fact:
    msg: |
      The installer and the mirror registry for the disconnected install are now ready.

      Refer to the instructions at the end of the {{ helper.mirror_registry_dir }}/mirror_sync.stdout.txt file on how to
      configure your install-config.yaml (add the imageContentSources element) to pull images from the mirror registry.

      If your mirror registry uses a self-signed certificate, you must add that certificate to the additionalTrustBundle
      element in your install-config.yaml.

      Also, remember to use {{ helper.mirror_registry_dir }}/pull-secret.json as your pull secret instead of the original
      pull secret that you downloaded from the Red Hat site. This updated pull secret contains credentials for the mirror
      registry as well.

- debug: msg="{{ msg.split('\n') }}"
