- name: Installing OpenShift in a restricted network
  set_fact:
    msg: |
      The installer and the mirror registry for the restricted network installation are now ready.

      Refer to the instructions at the end of the {{ helper.mirror_registry_dir }}/mirror_sync.{{ mirror_registry.openshift_install_repo }}.stdout.txt file
      on how to configure your install-config.yaml (add the imageContentSources element) to pull images from the mirror registry. Update your
      install-config.yaml accordingly.

      If your mirror registry uses a self-signed certificate, you must add that certificate to the additionalTrustBundle
      element in your install-config.yaml. The self-signed certificate can be found here: {{ helper.mirror_registry_dir }}/certs/domain.crt

      Also, remember to use {{ helper.mirror_registry_dir }}/pull-secret.json as your pull secret instead of the original
      pull secret that you downloaded from the Red Hat site. The new pull secret includes the original credentials for the Red Hat site as well as
      the credentials for the mirror registry.

- debug: msg="{{ msg.split('\n') }}"
