- name: Copy the mirroring script
  template:
    src: mirror.sh
    dest: '{{ helper.mirror_registry_dir }}/bin'
    mode: '0755'

- name: Waiting since {{ ansible_date_time.time }} for the mirroring process to complete
  command: '{{ helper.mirror_registry_dir }}/bin/mirror.sh'
  register: mirror_command

- debug:
    var: mirror_command.stderr_lines

- debug:
    var: mirror_command.stdout_lines

- name: Save standard error to file {{ helper.mirror_registry_dir }}/mirror.stderr.txt
  copy:
    dest: '{{ helper.mirror_registry_dir }}/mirror.stderr.txt'
    content: '{{ mirror_command.stderr }}'

- name: Save standard output to file {{ helper.mirror_registry_dir }}/mirror.stdout.txt
  copy:
    dest: '{{ helper.mirror_registry_dir }}/mirror.stdout.txt'
    content: '{{ mirror_command.stdout }}'
    backup: True
