- name: Ensure required directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ helper.timestamp_dir }}'

- name: Check if timestamp {{ helper.timestamp_ignition_created }} exists
  stat:
    path: '{{ helper.timestamp_ignition_created }}'
  register: timestamp_ignition_created

- name: Configure installer
  import_tasks: install_config_tasks.yml
  when: not timestamp_ignition_created.stat.exists

- name: Create timestamp {{ helper.timestamp_ignition_created }}
  file:
    path: '{{ helper.timestamp_ignition_created }}'
    state: touch
  when: not timestamp_ignition_created.stat.exists
