- name: Use DNS server from the system configuration
  set_fact:
    query_server: ''

- name: Use custom DNS server configuration
  set_fact:
    query_server: '@{{ check_dns.query_server }}'
  when: check_dns.query_server is defined

- name: Look up A records
  set_fact:
    a_records: >
      {{ a_records | default({}) | combine({ item: query('dig', '{{ query_server }}', '{{ item }}') }) }}
  loop: >
    {{
      (
        (openshift_cluster_hosts | json_query('[*].hostname')) +
        ['api', 'api-int', '*.apps']
      )
      | map('regex_replace', '^(.*)$', '\1.{{ openshift_install_config.cluster_domain }}')
      | list
    }}

- name: Look up PTR records
  set_fact:
    ptr_records: >
      {{ ptr_records | default({}) | combine({ item.ipaddr: query('dig', '{{ query_server }}', '{{ item.ipaddr }}/PTR') }) }}
  loop: '{{ openshift_cluster_hosts }}'
  when: "'master' in item.roles or 'infra' in item.roles or 'app' in item.roles"

- name: Display DNS query results
  set_fact:
    msg: |
      *** DNS INFO ***

      A Records:

      {% for item in a_records %}
      {{ "%64s"| format(item) }} = {{ a_records[item] }}
      {% endfor %}

      PTR Records:

      {% for item in ptr_records %}
      {{ "%15s"| format(item) }} = {{ ptr_records[item] }}
      {% endfor %}

- debug: msg="{{ msg.split('\n') }}"
