- name: Create a volume {{ libvirt_volume_name }} of size {{ libvirt_volume_size }} backed by {{ libvirt_volume_base }}
  shell: |
    VOLUME_NAME='{{ libvirt_volume_name }}'
    virsh \
      --connect '{{ libvirt.libvirt_connection_uri }}' \
      vol-info \
      --pool '{{ libvirt.pool_name }}' \
      "$VOLUME_NAME"
    if [ $? -ne 0 ]; then
      virsh \
        --connect  '{{ libvirt.libvirt_connection_uri }}' \
        vol-create-as \
        --pool '{{ libvirt.pool_name }}' \
        --name "$VOLUME_NAME" \
        --capacity {{ libvirt_volume_size }} \
        --allocation 0 \
        --format qcow2 \
        --backing-vol {{ libvirt_volume_base }} \
        --backing-vol-format qcow2 || exit 1
      echo CHANGED
    fi
  register: libvirt_volume
  changed_when: libvirt_volume is failed or libvirt_volume.stdout | regex_search('CHANGED')
  become: True