- name: Delete volume {{ libvirt_volume_name }}
  shell: |
    VOLUME_NAME='{{ libvirt_volume_name }}'
    virsh \
      --connect '{{ libvirt.libvirt_connection_uri }}' \
      vol-info \
      --pool '{{ libvirt.pool_name }}' \
      "$VOLUME_NAME"
    if [ $? -eq 0 ]; then
      virsh \
        --connect  '{{ libvirt.libvirt_connection_uri }}' \
        vol-delete \
        --pool '{{ libvirt.pool_name }}' \
        "$VOLUME_NAME" || exit 1
      echo CHANGED
    fi
  register: libvirt_volume
  changed_when: libvirt_volume is failed or libvirt_volume.stdout | regex_search('CHANGED')
  become: True