- name: Retrieve all existing machines
  virt:
    uri: '{{ libvirt.libvirt_connection_uri }}'
    command: list_vms
  register: libvirt_vms

- name: Define existing virtual machines
  set_fact:
    libvirt_existing_vms: '{{ libvirt_vms.list_vms }}'

- name: Create virtual machines that don't exist
  include_tasks: deploy_host.yml
  when: virtual_machine_names[item.hostname] not in libvirt_existing_vms
  with_items: '{{ openshift_cluster_hosts }}'