- name: Ensure libvirt client libraries are installed
  yum:
    name:
      - libvirt-client
      - '{{ rpm_name["libvirt-python"] }}'
    state: present
  become: True

- name: Ensure required directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ helper.web_cluster_dir }}'

- name: Download Red Hat CoreOS image for QEMU {{ coreos.qemu_qcow2_url }}
  get_url:
    url: '{{ coreos.qemu_qcow2_url }}'
    dest: '{{ helper.images_dir }}/{{ coreos.qemu_qcow2_url | basename }}'
    checksum: 'sha256:{{ coreos.sha256sum_url }}'

- name: Set image filename
  set_fact:
    libvirt_image_filename: '{{ helper.images_dir }}/{{ coreos.qemu_qcow2_url | basename | regex_replace("\.gz$", "") }}'

- name: Extract Red Hat CoreOS image for QEMU
  command: gunzip --keep '{{ helper.images_dir }}/{{ coreos.qemu_qcow2_url | basename }}'
  args:
    creates:
      '{{ libvirt_image_filename }}'