- name: Ensure libvirt client libraries are installed
  yum:
    name:
      - libvirt-client
      - '{{ rpm_name["libvirt-python"] }}'
    state: present
  become: True

- name: Ensure required directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ helper.web_cluster_dir }}'

- name: Download CoreOS binaries
  get_url:
    url: '{{ item }}'
    dest: '{{ helper.web_cluster_dir }}/{{ item | basename }}'
    checksum: 'sha256:{{ coreos.sha256sum_url }}'
  with_items:
    - '{{ coreos.installer_initramfs_url }}'
    - '{{ coreos.installer_kernel_url }}'
    - '{{ coreos.metal_bios_url }}'

- name: Ensure required directories exist
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ helper.tftp_cluster_dir }}'

- name: Create pxelinux.cfg configs
  template:
    src: files/generic/pxelinux.cfg/menu.cfg
    dest: '{{ helper.tftp_cluster_dir }}/pxelinux.cfg/01-{{ item.macaddr | regex_replace(":", "-") }}'
  with_items: '{{ openshift_cluster_hosts }}'