- name: Check if virtual machine template {{ ovirt.template_name }} already exists
  ovirt_template_info:
    auth: '{{ ovirt_auth }}'
    pattern: 'name="{{ ovirt.template_name }}" and cluster="{{ ovirt.cluster_name }}"'
  register: ovirt_template_info

- name: Create virtual machine template
  import_tasks: create_ovirt_template.yml
  when: ovirt_template_info.ovirt_templates | length == 0

- name: Retrieve all machines in the cluster {{ ovirt.cluster_name }}
  ovirt_vm_info:
    auth: '{{ ovirt_auth }}'
    pattern: 'cluster="{{ ovirt.cluster_name }}"'
  register: ovirt_vms

- name: Define existing virtual machines
  set_fact:
    ovirt_existing_vms: '{{ ovirt_vms.ovirt_vms | json_query("[*].name") }}'

- name: Create virtual machines that don't exist
  include_tasks: create_host.yml
  when: virtual_machine_names[item.hostname] not in ovirt_existing_vms
  with_items: '{{ openshift_cluster_hosts }}'
