- block:
    - name: Log in to '{{ ovirt.ovirt_url }}'
      ovirt_auth:
        url: '{{ ovirt.ovirt_url }}'
        username: '{{ ovirt.ovirt_username }}'
        password: '{{ ovirt.ovirt_password }}'
        insecure: True

    - name: Start newly created virtual machines
      include_tasks: start_host.yml
      when: virtual_machine_names[item.hostname] not in ovirt_existing_vms
      with_items: '{{ openshift_cluster_hosts }}'

  always:
    - name: Always revoke the SSO token, log out from '{{ ovirt.ovirt_url }}'
      ovirt_auth:
        state: absent
        ovirt_auth: '{{ ovirt_auth }}'
