- name: Power on baremetal machine
  ipmi_power:
    user: '{{ item.bmc.username }}'
    password: '{{ item.bmc.password }}'
    name: '{{ item.bmc.hostname }}'
    port: '{{ item.bmc.port }}'
    state: on
  with_items: '{{ openshift_cluster_hosts }}'
