- name: Download CoreOS binaries
  get_url:
    url: '{{ item }}'
    dest: '{{ helper.web_cluster_dir }}/{{ item | basename }}'
    checksum: 'sha256:{{ coreos.sha256sum_url }}'
  with_items:
    - '{{ coreos.installer_initramfs_url }}'
    - '{{ coreos.installer_kernel_url }}'
    - '{{ coreos.metal_bios_url }}'
